### ISSUE TITLE
Enable validation of an example payload

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [asyncapi/studio#200]
It would be cool to enable Studio to validate an example payload against the message schema.

This would enable quick prototyping and move into a direction of one tool to rule them all, as currently it is possible to use third party validator like https://www.jsonschemavalidator.net

**Comment by magicmatatjahu** [comment]
Thanks for the feature proposal! :)

> I don’t know, I thought it might help me, but not sure if someone feels the same restrictions since in the there are many json schema validators online (did not think of using those somehow)

Don't worry, it will be needed. Most likely we will do it as a separate panel where you can select a message/channel/scheme and validate the necessary inputs anyway.

**Comment by boyney123** [comment]
Thanks for the idea @ThanksForAllTheFish , think this is a great idea ➕

**Comment by magicmatatjahu** [comment]
Action points:
- create new component to render new "view" where we will support mentioned possibility:
  - it should have one `textarea` section where people will be able to pass the example payload/headers.
  - it should have `select` section where people will be able to select given `payload/headers` from existing AsyncAPI doc
  - it should have section where we will show possible errors.
- it should look like https://www.jsonschemavalidator.net/ but without that left input (there should be select section)
- the style should be consistent with the style of the rest of the application
- unit tests are welcome
- please don't focus on the integration (panel switching etc). It's nice to have but not required. We can make integration as followup after writing that new panel.

Before contribution please start discussion to clarify implementation and your questions/problems :)

This problem is involved in the [OpenForce event](https://github.com/asyncapi/website/pull/599). Please don't contribute if you are not participating in this event. If the problem is not solved at the end of the event, feel free to contribute :)
