### ISSUE TITLE
Beta label is almost invisible

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#209]
#### Describe the bug
The "beta" label near the logo became black and it's almost invisible.

#### How to Reproduce
Have a look at https://studio.asyncapi.com

![Captura de pantalla 2021-12-08 a las 18 42 53](https://user-images.githubusercontent.com/242119/145257373-26591c3e-cd53-4eef-841d-f937d3039eec.png)

#### Expected behavior
I was expecting it to be visible. I think it used to be cyan or white 🤔

**Comment by magicmatatjahu** [comment]
Right! Most likely some patch bump changed the styles, because it was always green :thinking:

**Comment by mcturco** [comment]
@fmvilas @magicmatatjahu it looks like the `text-teal-500` class doesn't exist anymore in the `default.min.css` file (Is that file sourced from the react component?) Comparing the version on @magicmatatjahu's PR with the live version, it looks like a class was added in front of each class, `.aui-root` which I think is causing some of the styles to fail.

![Screen Shot 2021-12-13 at 11 00 05 AM](https://user-images.githubusercontent.com/60163079/145846044-6f79b224-8920-4716-b35e-029ae5bd108c.png)

It is interesting too that the `text-pink-500` class loads from the `tailwind.css` source but the `text-teal-500` class doesn't. I wonder why? 

(Also, my apologies if this is not my place to investigate, I am interested in learning how the CSS workflow is on our products which is why I am trying to figure out what the bug is here! I hope that is okay 😃   and forgive me if the solution has already been found)

**Comment by mcturco** [comment]
Awesome! Thanks for the breakdown @magicmatatjahu and glad the issue is resolved! 😄
