### ISSUE TITLE
Docker image is broken "set-public-url.sh: applet not found"

### ISSUE THREAD

**Issue by svenwal** [asyncapi/studio#297]
#### Describe the bug
When trying to start any Docker image > 0.6.0 it fails starting with the following errors in the logs

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/set-public-url.sh
set-public-url.sh: applet not found

#### How to Reproduce
Try to start the Docker image as described in the README

#### Expected behavior
Docker starts and hosts AsyncAPI Studio (works with 0.6.0 bot no newer version)

**Comment by magicmatatjahu** [comment]
I use almost the latest docker `20.10.13` and macOS `12.1` and everything works for me including older versions. I think it must be a problem with your version of docker, or possibly your system - I remember that docker worked badly on windows, but I do not know what the situation is now, because I do not use that system for several years.

**Comment by magicmatatjahu** [comment]
@svenwal Will you give some info about your system/env?

**Comment by magicmatatjahu** [comment]
I am closing due to lack of response. Reopen when needed.
