### ISSUE TITLE
Add Jonas Lagoni to the codeowners

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/studio#484]
The Studio currently has 4 codeowners. Me, Fran, Missy and David. The problem is that Missy and David currently don't have much time for contributing and review because they are working in other projects or companies, so for "active" (I mean frequent) contribution there is only Fran and me, but Fran also has a lot of other things to do in org. I propose another codeowner, Jonas Lagoni. He has already tentatively agreed, but I need to ask you. Do you agree? 

cc @jonaslagoni @fmvilas @mcturco @boyney123

**Comment by fmvilas** [comment]
Why Jonas? He doesn't contribute much to this repo. As much as I understand your concern, it would not be fair to the community that we invite Jonas as a code owner for Studio. I wasn't aware of this problem and was completely ignoring this repo thinking there were other people taking care. Now that I'm aware, I'll review your PRs more frequently so you don't find bottlenecks.

That said, the next step should be to make a big effort to onboard new contributors to Studio so that we get rid of this situation at some point. Please use Community Meeting, Slack, or even blog posts to give visibility to this issue. @AceTheCreator might be able to help you to give it more visibility.

**Comment by jonaslagoni** [comment]
I agree with you @fmvilas, but I also understand the frustration from @magicmatatjahu side 🙂 

So if you can mitigate the time it takes for getting PRs reviewed and moved along with different means then that is definitely the better solution than adding me as codeowner 👍 Cause it's true I have not done much in this repo, and I would basically serve as a reviewer to move PRs along 😄

**Comment by AceTheCreator** [comment]
Yeah. I'd definitely ensure to make awareness and onboard folks to contribute to this project and I believe I should definitely lead by example by also actively contributing to it myself too :) @fmvilas

**Comment by jonaslagoni** [comment]
@magicmatatjahu  you can close this issue down I think 😄

**Comment by magicmatatjahu** [comment]
@jonaslagoni Yeah, thanks for pinging!
