### ISSUE TITLE
BASE_URL issue

### ISSUE THREAD

**Issue by sebastianvoss** [asyncapi/studio#550]
When using the docker image with parameter `BASE_URL` it seem to not work as expected. Accessing the path it results in an `404` error.

```
docker run -it -p 8000:80 -e BASE_URL=/test asyncapi/studio:0.16.0
# open http://localhost:8000/test will result in 404
```

**Comment by sebastianvoss** [comment]
I checked with version `0.18.1` and it has the same issue.

**Comment by dlouzan** [comment]
Interestingly, on a k8s cluster, this was working for us properly until 0.18.1 with no issues, but the latest 1.0.0 version broke it. Reverting to 0.18.1 fixed it for the time being.

@fgreinacher

**Comment by fgreinacher** [comment]
Seems that https://github.com/asyncapi/studio/pull/688/files broken this.

Will provide a fix.

**Comment by sebastianvoss** [comment]
I think it is still an issue. I just tested it with:
```
docker run -it -p 8000:80 -e BASE_URL=/test asyncapi/studio:1.0.0
```

**Comment by KhudaDad414** [comment]
@fgreinacher I tried to find the issue but I can't see where the issue is. the `BASE_URL_PLACEHOLDER` is being set up correctly and the `echo "find /usr/share/nginx/html/ -type f -print0 | xargs -0 sed -i \"s|${BASE_URL_PLACEHOLDER}|\${BASE_URL}|g\"" > $ENTRYPOINT_SCRIPT && chmod +x $ENTRYPOINT_SCRIPT` also works fine. can you see what is wrong here? 🤔

**Comment by KhudaDad414** [comment]
@sebastianvoss I will look into this.

**Comment by KhudaDad414** [comment]
@sebastianvoss I have tested it and it seems to be working fine.
when I run:
`docker run -it -p 8000:80 asyncapi/studio`
it works fine without any errors.

`docker run -it -p 8000:80 -e BASE_URL=/a/custom/path asyncapi/studio`
will give these errors for me which is expected since I am not hosting the static files there:
<img width="664" alt="Screenshot 2023-12-18 at 16 49 04" src="https://github.com/asyncapi/studio/assets/32505158/452d8c81-f389-4161-940e-8bb530684e8d">

**Comment by sebastianvoss** [comment]
@KhudaDad414 Thanks for your feedback. You are right, I had a wrong understanding of the `BASE_URL` parameter. I thought it is something like a context path which results the artefacts are hosted on that path. I changed my setup to rewrite the URL from `/a/custom/path asyncapi/studio` to `/` before passing the traffic to studio and everything works now.

Thanks again for the clarification.
