### ISSUE TITLE
Adapt Github Actions to make it work with monorepos

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#651]
The release process that we have on AsyncAPI is meant to work with repositories containing a single application or package. Since [we want to make this repo a monorepo](https://github.com/asyncapi/studio/pull/638), we need to adapt the release process too.

**Comment by Shurtu-gal** [comment]
@fmvilas can I work upon this?

**Comment by KhudaDad414** [comment]
@Shurtu-gal Actually I am working on it right now. 😄

**Comment by KhudaDad414** [comment]
/progress 90

[this PR](https://github.com/asyncapi/studio/pull/680) is going to solve the current issue that we are facing with `craco`. the workflow has been tested [here](https://github.com/KhudaDad414/.github/actions/workflows/if-nodejs-release.yml) but I haven't had a successful because of the docker issue in the `studio` app, in theory it should work in the main repo. other packages publish fine.

**Comment by KhudaDad414** [comment]
/progress 40

since we are using `docker` to publish the `studio` as a docker image, figuring out how to do it in a monorepo since there is no package-lock.json in each app, so the docker publishing process needs to be reevaluated.

**Comment by fmvilas** [comment]
In case it helps, I found this: https://github.com/npm/rfcs/issues/554.

**Comment by KhudaDad414** [comment]
/progress 95

changesets are going to replace the semantic-release processes. PR is ready for review. https://github.com/asyncapi/studio/pull/706
