### ISSUE TITLE
Radix-ui usage need an ADR

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#734]
Related to #678 

cc @fmvilas

**Comment by Amzani** [comment]
@fmvilas why did we choose Radix-UI ?, I can help write this ADR.

**Comment by fmvilas** [comment]
Libraries like Radix or [Headless UI](https://headlessui.com) have no implicit design. They're a set of components handling the logical part of them, not the design part. For instance, handling keyboard navigation, support for screen readers, checking if a menu has space to be rendered on the right and avoiding collisions with the limits of the window, etc. 

We need to build our set of components, our own UI library. If we use a ready-made library of components, we would be stuck to this library look and feel. Also, we would not have much freedom since the design is part of the library and their components have it integrated, often making it difficult or impossible to change it.

I evaluated Radix and Headless UI. Chose Radix because it's more complete, well maintained, and its community is more active.
