### ISSUE TITLE
Move plugins to their own repos

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/studio#8]
Currently, the plugins source code is located at a `plugins` folder on the root directory of the project. They should have their own repo, either one repo for each or a plugins repo.

**Comment by AceTheCreator** [comment]
I can actually implement this since I'm currently working on the google analytics plugin

**Comment by magicmatatjahu** [comment]
Since we're going with a different implementation of Studio (as a SPA app, rather than using NextJS) I'm closing this issue. In addition, the implementation of the current plugins works only on NodeJS and not in the browser (https://github.com/asyncapi/studio/pull/37#issuecomment-843366186), so we have to redefine them - probably have two types, for the frontend (https://github.com/asyncapi/asyncapi-react/issues/433) and backend (https://github.com/asyncapi/studio/issues/86).
