### ISSUE TITLE
Other issues types are missing

### ISSUE THREAD

**Issue by Amzani** [asyncapi/studio#826]
When creating [a new issue](https://github.com/asyncapi/studio/issues/new/choose), we don't see other issues types like in other repositories (e.g https://github.com/asyncapi/cli/issues/new/choose)

**Comment by Amzani** [comment]
@KhudaDad414 you probably have an idea how to pull https://github.com/asyncapi/.github/tree/master/.github/ISSUE_TEMPLATE

**Comment by KhudaDad414** [comment]
It is because we are using a custom issue template here and the `.github` issue templates are being ignored. we have two options here.
1) copy them over.
2) setup a new action in `.github` repo to replicate them to the studio.

I would personally go with the 1st option since they don't receive updates anyway. 🤷
